const REVIEW_RULES_BLOCK = [
  '## 审查原则',
  '- 以事实为准，只依据仓库证据下结论。',
  '- 优先核对 git 提交、变更文件和直接相关代码，不要凭空推断。',
  '- 关注功能正确性、回归风险、测试覆盖、边界条件和发布风险。',
  '- 如果证据不足，明确写出 scope limitation，不要把猜测写成结论。',
].join('\n');

const REPORT_STYLE_BLOCK = [
  '## 报告风格',
  '- 保持中文，简洁但具体。',
  '- 先给总体结论，再给可执行的发现和建议。',
  '- 每条问题都要说明影响、证据和建议修复方式。',
  '- 不要写空泛的总结句，尽量给出可落地的检查点。',
].join('\n');

export const REPO_REVIEW_FIXED_REPORT_TEMPLATE_BLOCK = [
  '## 固定报告模板',
  '最终正文必须使用下面的中文 Markdown 结构，不要改标题、不要省略章节：',
  '',
  '## 代码审查报告',
  '',
  '### 一、审查总结',
  '用 2-3 句话概括本次审查的整体结论（pass/warn/fail）、核心风险和建议。',
  '',
  '### 二、高风险问题',
  '如果有高风险 finding，每个问题严格按以下格式输出：',
  '',
  '🔴 [问题类型] 问题标题',
  '**文件：** `文件路径:行号`',
  '```<language>',
  '// 当前有问题的代码',
  '```',
  '**问题：** 描述问题的成因、触发条件和风险影响。',
  '**修复建议：**',
  '```<language>',
  '// 修复后的代码',
  '```',
  '',
  '### 三、中风险问题',
  '如果有中风险 finding，每个问题按以下格式：',
  '',
  '🟡 [问题类型] 问题标题',
  '**文件：** `文件路径:行号`',
  '```<language>',
  '// 当前有问题的代码',
  '```',
  '**问题：** 描述问题说明。',
  '**修复建议：**',
  '```<language>',
  '// 修复后的代码',
  '```',
  '',
  '### 四、低风险问题 / 代码规范',
  '如果有低风险 finding，每个问题按以下格式：',
  '',
  '🔵 [问题类型] 问题标题',
  '**文件：** `文件路径:行号`',
  '问题说明和修复建议（低风险可以简写，但仍需给出具体建议）。',
  '',
  '### 五、代码亮点',
  '如有值得肯定的设计，列出要点。',
  '',
  '### 六、总结',
  '在报告末尾输出统计表格：',
  '',
  '| 风险等级 | 数量 | 主要问题 |',
  '|---------|------|---------|',
  '| 🔴 高风险 | N | 一句话概括 |',
  '| 🟡 中风险 | N | 一句话概括 |',
  '| 🔵 低风险 | N | 一句话概括 |',
  '',
  '建议在合并前优先处理 N 个高风险问题。',
  '',
  '格式要求：',
  '- 每个问题必须包含问题代码片段，让开发者能定位到具体代码。',
  '- 高风险和中风险问题必须同时给出修复后的代码示例。',
  '- 如果某个风险等级没有问题，跳过该章节。',
  '- 无问题时在审查总结中明确说明“未发现明显问题”并指出代码的优点。',
  '- 除 overall、severity、confidence 这些枚举值外，所有面向用户的文本必须使用简体中文。',
].join('\n');

const REPO_REVIEW_PRIMARY_OUTPUT_BLOCK = [
  '## 输出协议',
  '只返回一个 JSON 对象，不要输出 Markdown 代码块。',
  'JSON 顶层字段至少包括：',
  '{',
  '  "schema_version": "repo_review.main.v1",',
  '  "result_type": "repo_review_final",',
  '  "final": true,',
  '  "overall": "pass | warn | fail | error | skipped",',
  '  "summary": "一句话总体结论",',
  '  "branch": "当前分支",',
  '  "diff_range": "本次审查范围，例如 base..head",',
  '  "confidence": "high | medium | low",',
  '  "findings": [',
  '    {',
  '      "severity": "high | medium | low",',
  '      "file": "相关文件，可为空",',
  '      "line": "相关行号或行号范围，例如 12 或 12-18",',
  '      "title": "问题标题",',
  '      "codeSnippet": "当前有问题的代码片段",',
  '      "fixCode": "修复后的代码示例，可为空",',
  '      "evidence": "补充证据或上下文，可为空",',
  '      "detail": "问题说明",',
  '      "suggestion": "修复建议，可为空"',
  '    }',
  '  ],',
  '  "file_reviews": [',
  '    {',
  '      "file": "文件路径",',
  '      "summary": "文件级结论",',
  '      "positives": ["做得好的点"],',
  '      "risks": ["风险点"],',
  '      "suggestions": ["建议"]',
  '    }',
  '  ],',
  '  "commit_reviews": [',
  '    {',
  '      "commit": "短 SHA",',
  '      "title": "提交标题",',
  '      "author": "作者",',
  '      "positives": ["亮点"],',
  '      "issues": ["问题"]',
  '    }',
  '  ],',
  '  "scope_limitations": ["证据限制"],',
  '  "suggestions": ["补充建议"],',
  '  "recommended_block": false,',
  '  "markdown_body": "可直接展示的人类可读报告"',
  '}',
].join('\n');

const OUTPUT_CONTRACT_BLOCK = [
  '## 输出协议',
  '只返回一个 JSON 对象，不要输出 Markdown 代码块。',
  'JSON 顶层字段至少包括：',
  '{',
  '  "schema_version": "repo_review.main.v1",',
  '  "result_type": "repo_review_final",',
  '  "final": true,',
  '  "overall": "pass | warn | fail | error | skipped",',
  '  "summary": "一句话总体结论",',
  '  "branch": "当前分支",',
  '  "diff_range": "本次审查范围，例如 base..head",',
  '  "confidence": "high | medium | low",',
  '  "findings": [',
  '    {',
  '      "severity": "high | medium | low",',
  '      "file": "相关文件，可为空",',
  '      "line": "相关行号或行号范围，例如 12 或 12-18",',
  '      "title": "问题标题",',
  '      "codeSnippet": "当前有问题的代码片段",',
  '      "fixCode": "修复后的代码示例，可为空",',
  '      "evidence": "补充证据或上下文，可为空",',
  '      "detail": "问题说明",',
  '      "suggestion": "修复建议，可为空"',
  '    }',
  '  ],',
  '  "file_reviews": [',
  '    {',
  '      "file": "文件路径",',
  '      "summary": "文件级结论",',
  '      "positives": ["做得好的点"],',
  '      "risks": ["风险点"],',
  '      "suggestions": ["建议"]',
  '    }',
  '  ],',
  '  "commit_reviews": [',
  '    {',
  '      "commit": "短 SHA",',
  '      "title": "提交标题",',
  '      "author": "作者",',
  '      "positives": ["亮点"],',
  '      "issues": ["问题"]',
  '    }',
  '  ],',
  '  "scope_limitations": ["证据限制"],',
  '  "suggestions": ["补充建议"],',
  '  "recommended_block": false,',
  '  "markdown_body": "可直接展示的人类可读报告"',
  '}',
].join('\n');

const REVIEW_PLAN_OUTPUT_CONTRACT_BLOCK = [
  '## 第一轮输出协议',
  '你现在只制定审查计划，不要输出最终审查结论。',
  '最终格式化整理阶段会生成 markdown_body；第一轮不要生成最终报告正文。',
  '只返回一个 JSON 对象，不要输出 Markdown 代码块。',
  '如果“全文读取能力”为 disabled，所有 tasks[].full_file_files 和 full_file_review_files 必须返回空数组 []。',
  'JSON 顶层字段必须是 review_plan：',
  '{',
  '  "review_plan": {',
  '    "should_delegate": false,',
  '    "delegation_reason": "不委派或委派的原因",',
  '    "tasks": [',
  '      {',
  '        "id": "task-1",',
  '        "title": "任务标题",',
  '        "objective": "子代理要完成的局部 CR 目标",',
  '        "files": ["只允许来自变更范围的文件路径"],',
  '        "focus": "模块、风险主题或测试覆盖重点",',
  '        "full_file_files": ["需要全文读取的文件路径"]',
  '      }',
  '    ],',
  '    "full_file_review_files": ["主代理认为需要全文审查的变更文件"],',
  '    "risk_areas": ["预计风险点"],',
  '    "notes": ["计划说明或限制"]',
  '  }',
  '}',
].join('\n');

const REPO_REVIEW_AGENTIC_BUDGET_BLOCK = [
  '## 系统预算',
  '变更文件数：{{changedFileCount}}',
  'Diff 大小：{{diffBytes}} bytes',
  '建议委派阈值：{{delegationFileThreshold}} 个文件',
  '最多可委派子代理：{{maxSubagents}}',
  '全文读取能力：{{fullFileReviewEnabled}}',
  '单文件全文读取上限：{{maxFullFileBytesPerFile}} bytes',
  '本次总读取预算：{{maxTotalReadBytes}} bytes',
  '最大审查轮次：{{maxReviewRounds}}',
  '格式化整理器：{{extractorEnabled}}',
].join('\n');

const REPO_REVIEW_AGENTIC_PLAN_BLOCK = [
  '## 主审查代理职责',
  '- 你是唯一负责审查策略和最终结论的主审查代理。',
  '- 第一轮必须先制定 review_plan，决定是否委派。',
  '- 子代理只用于扩大覆盖和并行取证；最终严重性、去重、跨文件影响和阻断建议由你负责。',
  '- 如果不委派，必须在 delegation_reason 中写明原因。',
  '- 只有变更文件数超过建议委派阈值，或确有跨模块高风险需要并行取证时才委派；低风险小改动由主代理自己审查。',
  '- 如果超过建议委派阈值，优先考虑按图谱社区、模块、风险主题或测试覆盖分配少量任务。',
  '- 任务文件必须来自变更文件列表；需要相关未变更文件时，在 notes 说明原因，不要把它写进子代理 files。',
].join('\n');

const REPO_REVIEW_AGENTIC_PLAN_ONLY_BLOCK = [
  '## 计划阶段约束',
  '- 只使用系统已准备的 diff、提交摘要、Review Evidence Bundle、CodeMap 和 Code Index 上下文制定 review_plan。',
  '- 计划阶段不要调用工具，不要读取仓库，不要执行 git diff。',
  '- 计划里只描述后续如何审查与是否委派，不要直接输出最终审查结论。',
  '- 需要后续继续取证的点写入 risk_areas 或 notes，不要把它们伪装成已确认问题。',
  '- 子代理数量必须按实际需要给出，不要为了用满预算而创建全部可用子代理。',
  '- tasks[].files 和 full_file_review_files 只能来自变更文件列表。',
  '- 若不委派，必须明确说明不委派原因。',
].join('\n');

const AGENT_TOOL_BLOCK = [
  '## 取证工具',
  '- 仓库只读挂载在 `/workspace/extra`。',
  '- 优先使用本提示中的 diff/evidence/CodeMap/Code Index 上下文，不要固定先跑 `git diff`。',
  '- evidence 不足时再用 `git diff`、`git log`、`read_file` 或 `rg` 做只读补证。',
  '- 不要把“没有直接给出 diff 文本”当成障碍；必要时自己补充取证。',
  '- 需要看单个文件时，优先用 `read_file` 或 `git show` 读取实际内容。',
  '- 如果结论需要跨文件确认，再继续读相关文件，不要只看文件名下结论。',
].join('\n');

const REPO_REVIEW_DASHBOARD_BLOCK = [
  '## 审查范围',
  '仓库：{{repositoryName}}',
  '{{primaryLanguageBlock}}',
  '阶段：{{stage}}',
  '来源：{{source}}',
  '执行人：{{actor}}',
  '分支：{{branch}}',
  '基线提交：{{baseSha}}',
  '目标提交：{{headSha}}',
  '取证范围：{{diffRange}}',
  '{{commitSummaryBlock}}',
  '{{evidenceBundleBlock}}',
  '{{graphPlanningBlock}}',
  '{{impactGraphBlock}}',
  '{{contextLimitationsBlock}}',
  '变更文件：',
  '{{changedFiles}}',
  '变更概览：',
  '{{diffSummaryBlock}}',
].join('\n');

const REPO_REVIEW_AGENTIC_DASHBOARD_BLOCK = [
  '## 审查范围',
  '仓库：{{repositoryName}}',
  '{{primaryLanguageBlock}}',
  '阶段：{{stage}}',
  '来源：{{source}}',
  '执行人：{{actor}}',
  '分支：{{branch}}',
  '基线提交：{{baseSha}}',
  '目标提交：{{headSha}}',
  '取证范围：{{diffRange}}',
  '{{commitSummaryBlock}}',
  '{{evidenceBundleBlock}}',
  '{{impactGraphBlock}}',
  '{{contextLimitationsBlock}}',
  '变更文件：',
  '{{changedFiles}}',
  '变更概览：',
  '{{diffSummaryBlock}}',
  '',
  '{{workspaceInspectionInstructions}}',
  '{{fullFileReviewInstructions}}',
  '{{customPromptBlock}}',
].join('\n');

const REPO_REVIEW_FILE_CONTEXT_BLOCK = [
  '## 审查范围',
  '仓库：{{repositoryName}}',
  '{{primaryLanguageBlock}}',
  '分支：{{branch}}',
  '基线提交：{{baseSha}}',
  '目标提交：{{headSha}}',
  '取证范围：{{diffRange}}',
  '目标文件：{{filePath}}',
  '主审查摘要：{{primarySummary}}',
  '相关发现：',
  '{{relatedFindings}}',
  '',
  '该文件本次 diff：',
  '{{fileDiff}}',
  '',
  '该文件当前完整内容：',
  '{{fileContent}}',
].join('\n');

const REPO_REVIEW_ORCHESTRATOR_TASK_BLOCK = [
  '## 任务分发',
  '- 这是一个全文件补充审查 orchestrator。',
  '- 你要为每个任务分配 Agent 子代理，子代理只负责自己分到的文件。',
  '- 先并行派发，再汇总结果，不要自己替每个文件补读全部内容。',
  '- 最终返回 JSON，其中 files 数组里每个元素对应一个文件或一个分组。',
  '## 并发提示',
  '{{concurrencyHint}}',
  '## 分发指令',
  '{{dispatchInstruction}}',
  '## 子代理返回结构',
  '{{perAgentSchema}}',
  '## 任务清单',
  '{{taskBlocks}}',
].join('\n');

export const REPO_REVIEW_PRIMARY_TEMPLATE = [
  REPO_REVIEW_DASHBOARD_BLOCK,
  '',
  '{{fullFileReviewInstructions}}',
  '{{workspaceInspectionInstructions}}',
  '{{customPromptBlock}}',
  '',
  '## 可追踪取证建议',
  '- 优先使用系统已经提供的 diff、evidence 和上下文；证据不足时再用只读工具补证。',
  '- 优先直接使用 `git diff {{diffRange}} -- <file>`、`git log`、`rg`、`read_file` 或读取直接相关文件；不要把这些只读命令包进 `bash -lc` 之类的包装器。',
  '- 工具调用会展示在审查进度里，便于确认你读了哪些文件、核对了哪些片段；小改动不需要穷尽全仓。',
  '- 优先核对高风险文件、SQL/配置/接口边界、测试缺口和跨文件调用关系；证据足够后直接给结论。',
  '',
  '## 任务',
  '请完成代码审查，输出结构化 JSON。',
  '你可以按自己认为合适的方式组织取证和判断；重点是结论清楚、证据具体、建议可执行。',
  '如果需要用仓库工具补充核对，可以使用只读工作区；如果提示内 evidence 已足够，也可以直接完成审查。',
  '',
  REPO_REVIEW_PRIMARY_OUTPUT_BLOCK,
].join('\n');

export const REPO_REVIEW_AGENTIC_PLAN_TEMPLATE = [
  REPO_REVIEW_AGENTIC_DASHBOARD_BLOCK,
  '',
  REPO_REVIEW_AGENTIC_BUDGET_BLOCK,
  '',
  REPO_REVIEW_AGENTIC_PLAN_BLOCK,
  '',
  REPO_REVIEW_AGENTIC_PLAN_ONLY_BLOCK,
  '',
  REVIEW_RULES_BLOCK,
  '',
  REVIEW_PLAN_OUTPUT_CONTRACT_BLOCK,
].join('\n');

export const REPO_REVIEW_AGENTIC_SUBAGENT_TEMPLATE = [
  [
    '## 局部 CR 子代理任务',
    '仓库：{{repositoryName}}',
    '分支：{{branch}}',
    '基线提交：{{baseSha}}',
    '目标提交：{{headSha}}',
    '取证范围：{{diffRange}}',
    '任务 ID：{{taskId}}',
    '任务标题：{{taskTitle}}',
    '任务目标：{{taskObjective}}',
    '任务重点：{{taskFocus}}',
    '允许文件：',
    '{{taskFiles}}',
    '允许全文读取文件：',
    '{{fullFileFiles}}',
    '{{projectContextBlock}}',
    'Diff slice：',
    '{{diffSlice}}',
  ].join('\n'),
  '',
  '## 约束',
  '- 你只执行本任务范围内的局部 CR，不写最终总报告。',
  '- 只依据本提示中的任务文件、Diff slice、项目上下文和其他 evidence 判断。',
  '- 不要调用工具、读取仓库、执行 git 命令、创建或派发子代理。',
  '- 输出必须是面向主代理阅读的中文 Markdown，不要输出 JSON。',
  '- 如果某处证据不足，直接说明，不要编造结构化字段。',
  '',
  '{{customPromptBlock}}',
  '',
  REVIEW_RULES_BLOCK,
  '',
  '## 输出要求',
  '- 只输出一个 Markdown 报告，不要输出 JSON。',
  '- 必须包含以下小节：',
  '  - 任务范围',
  '  - 已检查内容',
  '  - 确认问题',
  '  - 需要主代理继续确认',
  '  - 结论',
  '- 在结论里给出置信度：high | medium | low。',
  '- 确认问题部分按严重性分段或用清晰的项目符号表达。',
].join('\n');

export const REPO_REVIEW_AGENTIC_FINAL_TEMPLATE = [
  REPO_REVIEW_AGENTIC_DASHBOARD_BLOCK,
  '',
  REPO_REVIEW_AGENTIC_BUDGET_BLOCK,
  '',
  '## 已批准的审查计划',
  '{{reviewPlan}}',
  '',
  '## 子代理证据摘要',
  '{{subagentResults}}',
  '',
  AGENT_TOOL_BLOCK,
  '',
  REVIEW_RULES_BLOCK,
  '',
  REPORT_STYLE_BLOCK,
  '',
  OUTPUT_CONTRACT_BLOCK,
].join('\n');

export const REPO_REVIEW_AGENTIC_EXTRACTOR_TEMPLATE = [
  '## 格式化整理任务',
  '你负责把主审查 Markdown 和补充子代理结果整理成结构化 JSON，并产出最终可直接展示的报告正文。',
  '不要重新审查代码，不新增输入里没有的事实。',
  '可以纳入补充子代理结果中的 findings、file_reviews、suggestions 和 scope_limitations。',
  '如果输入没有提供某字段，只能在 scope_limitations 中标注，不要补造问题。',
  'markdown_body 必须是可直接展示的中文 Markdown，并严格采用下面的固定报告模板。',
  REPO_REVIEW_FIXED_REPORT_TEMPLATE_BLOCK,
  '',
  '## 主审查报告',
  '{{mainReportMarkdown}}',
  '',
  '## 补充子代理结果',
  '{{subagentResults}}',
  '',
  OUTPUT_CONTRACT_BLOCK,
].join('\n');

export const REPO_REVIEW_DIFF_WORKER_TEMPLATE = [
  [
    '## 文件分组审查',
    '仓库：{{repositoryName}}',
    '分支：{{branch}}',
    '基线提交：{{baseSha}}',
    '目标提交：{{headSha}}',
    '取证范围：{{diffRange}}',
    '本组文件数：{{fileCount}}',
    '文件列表：',
    '{{groupFiles}}',
  ].join('\n'),
  '',
  '{{customPromptBlock}}',
  '',
  '## 单文件取证',
  '- 针对单个文件时，优先用 `git -C /workspace/extra diff {{diffRange}} -- <file>`。',
  AGENT_TOOL_BLOCK,
  '',
  REVIEW_RULES_BLOCK,
  '',
  REPORT_STYLE_BLOCK,
  '',
  OUTPUT_CONTRACT_BLOCK,
].join('\n');

export const REPO_REVIEW_SPLIT_MAIN_TEMPLATE = [
  [
    '## 跨文件主审查',
    '仓库：{{repositoryName}}',
    '分支：{{branch}}',
    '执行人：{{actor}}',
    '基线提交：{{baseSha}}',
    '目标提交：{{headSha}}',
    '取证范围：{{diffRange}}',
    '提交摘要：',
    '{{commitSummaryBlock}}',
    '已变更文件：',
    '{{changedFiles}}',
    '子代理发现：',
    '{{workerFindings}}',
  ].join('\n'),
  '',
  '{{customPromptBlock}}',
  '',
  AGENT_TOOL_BLOCK,
  '',
  REVIEW_RULES_BLOCK,
  '',
  REPORT_STYLE_BLOCK,
  '',
  OUTPUT_CONTRACT_BLOCK,
].join('\n');

export const REPO_REVIEW_SUPPLEMENTAL_FILE_TEMPLATE = [
  REPO_REVIEW_FILE_CONTEXT_BLOCK,
  '',
  '{{customPromptBlock}}',
  '',
  '## 子代理约束',
  '- 你只能使用本提示中提供的目标文件、diff、相关发现和完整内容审查。',
  '- 不要调用工具、读取仓库、执行 git 命令、派发子代理或扩展到未提供的文件。',
  '- 如果完整内容被截断或缺失，必须写入 scope_limitations。',
  '- 输出必须是面向主代理阅读的中文 Markdown，不要输出 JSON。',
  '- 如果证据不足，直接说明，不要编造结构化字段。',
  '',
  REVIEW_RULES_BLOCK,
  '',
  REPORT_STYLE_BLOCK,
  '',
  '## 输出要求',
  '- 只输出一个 Markdown 报告，不要输出 JSON。',
  '- 必须包含以下小节：',
  '  - 任务范围',
  '  - 已检查内容',
  '  - 确认问题',
  '  - 需要主代理继续确认',
  '  - 结论',
  '- 在结论里给出置信度：high | medium | low。',
].join('\n');

export const REPO_REVIEW_SUPPLEMENTAL_ORCHESTRATOR_TEMPLATE = [
  REPO_REVIEW_ORCHESTRATOR_TASK_BLOCK,
  '',
  '{{customPromptBlock}}',
  '',
  AGENT_TOOL_BLOCK,
  '',
  REVIEW_RULES_BLOCK,
  '',
  REPORT_STYLE_BLOCK,
  '',
  OUTPUT_CONTRACT_BLOCK,
].join('\n');

export const REPO_REVIEW_WORKER_OUTPUT_CONTRACT_BLOCK = [
  '## 输出协议',
  '只返回一个 JSON 对象，不要输出 Markdown 代码块。',
  '{',
  '  "schema_version": "repo_review.worker.v1",',
  '  "result_type": "repo_review_worker",',
  '  "final": true,',
  '  "checked_files": ["已检查的文件路径"],',
  '  "findings": [',
  '    {',
  '      "severity": "high | medium | low",',
  '      "file": "相关文件，可为空",',
  '      "line": "相关行号或行号范围，例如 12 或 12-18",',
  '      "title": "问题标题",',
  '      "codeSnippet": "当前有问题的代码片段",',
  '      "fixCode": "修复后的代码示例，可为空",',
  '      "evidence": "补充证据或上下文，可为空",',
  '      "detail": "问题说明",',
  '      "suggestion": "修复建议，可为空"',
  '    }',
  '  ],',
  '  "scope_limitations": ["证据限制"],',
  '  "confidence": "high | medium | low",',
  '  "needs_cross_file_reduction": false',
  '}',
].join('\n');

export const REPO_REVIEW_REDUCER_OUTPUT_CONTRACT_BLOCK = [
  '## 输出协议',
  '只返回一个 JSON 对象，不要输出 Markdown 代码块。',
  '{',
  '  "schema_version": "repo_review.reducer.v1",',
  '  "result_type": "repo_review_final",',
  '  "final": true,',
  '  "overall": "pass | warn | fail | error | skipped",',
  '  "summary": "一句话总体结论",',
  '  "branch": "当前分支",',
  '  "diff_range": "本次审查范围，例如 base..head",',
  '  "findings": [',
  '    {',
  '      "severity": "high | medium | low",',
  '      "file": "相关文件，可为空",',
  '      "line": "相关行号或行号范围，例如 12 或 12-18",',
  '      "title": "问题标题",',
  '      "codeSnippet": "当前有问题的代码片段",',
  '      "fixCode": "修复后的代码示例，可为空",',
  '      "evidence": "补充证据或上下文，可为空",',
  '      "detail": "问题说明",',
  '      "suggestion": "修复建议，可为空"',
  '    }',
  '  ],',
  '  "scope_limitations": ["证据限制"],',
  '  "suggestions": ["补充建议"],',
  '  "recommended_block": false,',
  '  "markdown_body": "可直接展示的人类可读报告"',
  '}',
].join('\n');

export const REPO_REVIEW_WORKER_TEMPLATE = [
  [
    '## 受控审查 Worker',
    '仓库：{{repositoryName}}',
    '分支：{{branch}}',
    '基线提交：{{baseSha}}',
    '目标提交：{{headSha}}',
    '取证范围：{{diffRange}}',
    'Worker ID：{{workerId}}',
    'Worker 标题：{{workerTitle}}',
    '文件列表：',
    '{{workerFiles}}',
    '证据块：',
    '{{workerEvidence}}',
  ].join('\n'),
  '',
  '{{customPromptBlock}}',
  '',
  '## 约束',
  '- 你只能依据本提示中的证据做局部审查。',
  '- 不要读取仓库、调用工具、派生子代理或扩展到未提供的文件。',
  '- 如果证据不足，把限制写入 scope_limitations，不要猜测。',
  '',
  REPO_REVIEW_WORKER_OUTPUT_CONTRACT_BLOCK,
].join('\n');

export const REPO_REVIEW_REDUCER_TEMPLATE = [
  [
    '## 审查收敛器',
    '仓库：{{repositoryName}}',
    '分支：{{branch}}',
    '基线提交：{{baseSha}}',
    '目标提交：{{headSha}}',
    '取证范围：{{diffRange}}',
    '已变更文件：',
    '{{changedFiles}}',
    'Worker 结果：',
    '{{workerResults}}',
  ].join('\n'),
  '',
  '{{customPromptBlock}}',
  '',
  '## 约束',
  '- 你只能依据全局元数据和 worker 结构化结果收敛结论。',
  '- 不要重新读取仓库，不要回灌 worker 原始 Markdown 或 rawOutput。',
  '- 需要跨文件归因时，优先合并重复发现并写入 scope_limitations。',
  '',
  REPO_REVIEW_REDUCER_OUTPUT_CONTRACT_BLOCK,
].join('\n');

export const REPO_REVIEW_DIGEST_TEMPLATE = [
  [
    '## 项目日报 / 周报',
    '你是一个项目经理助手，负责根据 Git 提交记录撰写代码项目日报或周报。',
    '类型：{{typeLabel}}',
    '仓库：{{repositoryName}}',
    '周期：{{periodLabel}}',
    '开始时间：{{periodStart}}',
    '结束时间：{{periodEnd}}',
    '工作目录：/workspace/extra（只读挂载）',
    '分支数：{{branchCount}}',
    '提交数：{{totalCommits}}',
    '贡献者数：{{contributorCount}}',
    '默认分支：{{defaultBranch}}',
    '',
    '## 各分支提交记录',
    '{{branchDetails}}',
    '',
    '## 重点提交',
    '{{sampledSection}}',
    '',
    '## 写作要求',
    '- 先概括整体变化，再分主题或分分支展开。',
    '- 必须提到仓库名、时间窗、主要分支和提交统计。',
    '- 可使用 `git -C /workspace/extra show <sha>`、`git log`、`git diff` 核对重点提交。',
    '- 结合提交信息和实际 diff 说明发生了什么，不要写空泛空话。',
    '- 如果某个分支没有明显产出，也要明确说明。',
    '- 输出中文 Markdown，直接适合发给团队成员阅读。',
  ].join('\n'),
  '',
  '## 建议结构',
  '- 标题：仓库名 + 时间窗。',
  '- 摘要：1-2 段概括。',
  '- 分支 / 主题进展：按分支或工作流块展开。',
  '- 重点提交：列出最有代表性的提交和原因。',
  '- 风险与后续：列出未完成事项、风险、待跟进点。',
].join('\n');

export const REPO_REVIEW_PROMPT_TEMPLATES = {
  'repo_review.primary': REPO_REVIEW_PRIMARY_TEMPLATE,
  'repo_review.worker': REPO_REVIEW_WORKER_TEMPLATE,
  'repo_review.reducer': REPO_REVIEW_REDUCER_TEMPLATE,
  'repo_review.agentic_plan': REPO_REVIEW_AGENTIC_PLAN_TEMPLATE,
  'repo_review.agentic_subagent': REPO_REVIEW_AGENTIC_SUBAGENT_TEMPLATE,
  'repo_review.agentic_final': REPO_REVIEW_AGENTIC_FINAL_TEMPLATE,
  'repo_review.agentic_extractor': REPO_REVIEW_AGENTIC_EXTRACTOR_TEMPLATE,
  'repo_review.supplemental_file': REPO_REVIEW_SUPPLEMENTAL_FILE_TEMPLATE,
  'repo_review.digest': REPO_REVIEW_DIGEST_TEMPLATE,
} as const;

export type RepoReviewPromptKey = keyof typeof REPO_REVIEW_PROMPT_TEMPLATES;
